[project]
name = "robotframework-relukko"
authors = [
    {name = "Reto Zingg", email = "g.d0b3rm4n@gmail.com"},
]
readme = "README.md"

# https://pypi.org/pypi?%3Aaction=list_classifiers
# "Development Status :: 3 - Alpha",
classifiers = [
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: MIT License",
    "Framework :: Robot Framework :: Library",
]
requires-python = ">=3.12"
dynamic = ["version", "description"]
dependencies = [
    "requests >=2.32.3",
    "robotframework >=7.1",
]

[tool.flit.module]
name = "Relukko"

[project.urls]
Homepage = "https://gitlab.com/relukko/robotframework-relukko"
Issues = "https://gitlab.com/relukko/robotframework-relukko/-/issues"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"