[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "temporal_embeddings_compass"
version = "0.4.4"
authors = [
{ name="Daniel Palamarchuk", email="d4n1elp@vt.edu" },
]
description = "A package for creating temporal embeddings with a compass"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "umap-learn",
    "hdbscan",
    "numpy",
    "pandas",
    "plotly",
    "scipy",
]
[project.urls]
"Homepage" = "https://github.com/danilka4/ttec.git"
"Bug Tracker" = "https://github.com/danilka4/tec/pulls"
[tool.hatch.build.targets.wheel]
name = "temporal_embeddings_compass"
packages = ["cade"]
[tool.hatch.metadata]
allow-direct-references = true

