[project]
name = "kiln-server"
version = "0.5.2"
requires-python = ">=3.10"
description = 'Kiln AI Server'
readme = "README.md"
license = {file = "LICENSE.txt"}
authors = [
  {name = "Steve Cosman, Chesterfield Laboratories Inc", email = "scosman@users.noreply.github.com"}
]
classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12"
]

dependencies = [
    "fastapi>=0.115.4",
    "httpx>=0.27.2",
    "kiln-ai>=0.5.3",
    "pydantic>=2.9.2",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.32.0",
]

[dependency-groups]
dev = [
    "isort>=5.13.2",
    "pyright==1.1.376",
    "pytest-asyncio>=0.24.0",
    "pytest>=8.3.3",
    "python-dotenv>=1.0.1",
    "ruff>=0.7.1",
]


[tool.uv.sources]
# This works fine, if we don't use UV workspace mode (top level pyproject.toml), but errors if we do.
# kiln-ai = { path = "../core" }

# This returns "ModuleNotFoundError: No module named 'kiln_ai'" in workspace mode, if included here, or not included at all.
kiln-ai = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://getkiln.ai"
Repository = "https://github.com/Kiln-AI/kiln"
Documentation = "https://github.com/Kiln-AI/kiln#readme"
Issues = "https://github.com/Kiln-AI/kiln/issues"
