[build-system]
requires = ['setuptools>=42', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'finance_calculator'
version = '0.1.0'
description = 'Это финансовый калькулятор, делай с ним че хочешь'
authors = [
  {name = 'Novoselov Efim', email = 'myemail@example.com'}
]
readme = 'README.md'
license = {text = 'MIT'}
requires-python = '>=3.10'
dependencies = [
  'requests>=2.25.1',
  'numpy>=1.19.2'
]