[package]
name = "dirman"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "dirman"
crate-type = ["cdylib","rlib"]

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module","auto-initialize"] }
walkdir = "2.3"
fuzzy-matcher = "*"

