[project]
name = "lexi-align"
version = "0.1.0"
description = "Word alignment between two languages using structured generation"
readme = "README.md"
authors = [
    { name = "Bor HodoÅ¡Äek", email = "dev@bor.space" }
]
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.9.0",
]

[project.optional-dependencies]
litellm = ["litellm>=1.51.0"]
dev = [
    "pytest>=7.0.0",
    "litellm>=1.51.0",
    "requests>=2.31.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "pandas>=2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "boto3>=1.35.50",
    "mypy>=1.13.0",
    "pandas-stubs",
    "types-tqdm",
    "types-requests",
]
