[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "water-column-sonar-processing"
version = "0.0.1"
authors = [
  { name="Rudy Klucik", email="rudy.klucik@noaa.gov" },
]
description = "A processing tool for water column sonar data."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/CI-CMG/water-column-sonar-processing"
Issues = "https://github.com/CI-CMG/water-column-sonar-processing/issues"