[tool.poetry]
name = "Magazine"
version = "0.1"
description = "Let your code take comprehensive notes and publish notes and figures as a beautiful consolidated PDF document."
authors = ["Martin Schr√∂n <martin@schroen.eu>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/mschroen/magazine"
repository = "https://github.com/mschroen/magazine"
keywords = ["logging", "reports", "pdf"]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">3.9"
numpy = ">2.0"
fpdf2 = ">2.8"
loguru = ">0.7"

[tool.poetry.dev-dependencies]
pytest = ">3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
