[build-system]
requires = [
    "hatchling>=1.22.2"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_s3"
version = "0.7.0"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (S3 storage modules)"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "pip>=24.3.1",
    "pypomes_core>=1.5.9",
    "setuptools>=75.3.0",
    "Unidecode>=1.3.8",
    "wheel>=0.44.0"
#   "boto3>=1.35.51"
#   "minio>=7.2.10"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-S3"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-S3/issues"
