[tool.poetry]
name = "brainframe-apps"
version = "0.4.3.4"
description = "BrainFrame Apps use BrainFrame REST API to interact with the BrainFrame OS"
authors = ["Stephen Li <stephen@aotu.ai>"]
license = "BSD License"
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = "^3.12,<4.0"
python_i18n = "^0.3.9"
requests = "^2.32.3"
brainframe-api = "^0.29.1"
typing-extensions = "4.10.0"
matplotlib = ">=3.5.0,<3.6.0"
numpy = "^1.26.4"
Pillow = ">=7.0.0,<12.0.0"
pytz = "^2019.3"
requests_oauthlib = "^1.3.0"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
isort = "^5.7.0,<5.8.0"
typing-extensions = "^4.10.0"

[tool.poetry.scripts]
brainframe-apps                      = 'brainframe_apps.cli:cli_main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
