[project]
name = "step-functions-sandbox-client"
version =   "0.1.2a8"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "boto3>=1.29.7",
    "boto3-stubs[cloudformation,s3,sqs,stepfunctions,sts]>=1.29.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
  "src/**/*.py"
]