[build-system]
requires = [
    "hatchling>=1.22.2"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_logging"
version = "0.4.8"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (logging module)"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "Flask>=3.0.3",
    "pip>=24.3.1",
    "pypomes_core>=1.5.9",
    "setuptools>=75.3.0",
    "wheel>=0.44.0"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-Logging"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-Logging/issues"
