[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py-linux-capabilities"
version = "0.1.2"
description = "A Python library providing an enumeration of Linux capabilities."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [
    { name="damwiw" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux"
]

[project.urls]
"Homepage" = "https://github.com/damwiw/py-linux-capabilities"

[tool.setuptools.packages.find]
where = ["src"]
