[tool.poetry]
name = "restack_integrations_gemini"
version = "0.0.4"
description = "Gemini integration for Restack AI"
authors = [
    "Restack Team <service@restack.io>"
]
packages = [{ include = "restack_integrations_gemini", from = "src" }]
include = ["src/restack_integrations_gemini/py.typed"]

readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.9.2"
restack_ai = "^0.0.11"
google-generativeai = "^0.8.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"