[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "get_processor_codename"
version = "0.0.2"
authors = [
  { name="SamuelLouf" },
]
description = "Easily get an intel processor's code name in Python."
readme = "README.md"
requires-python = ">=3"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python :: 3",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Topic :: System",
  "Topic :: System :: Hardware",
]

[project.urls]
Homepage = "https://github.com/samuellouf/get-processor-codename"
Issues = "https://github.com/samuellouf/get-processor-codename/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/get_processor_codename"]