[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[project]
name = "aidataup"
version = "0.0.5"
authors = [
  { name="dData", email="user@data.co.th" },
]
description = "aidataup"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "phonenumbers>=8.12.50",
    "pandas>=2.0.0",
    "mysql-connector-python",
    "psycopg2",
    "pysqlite3",
    "pysqlite3-binary",
    "requests"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
