# {# pkglts, pyproject.build
[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # , "setuptools-scm"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"  # we don't know if we need it
# #}

# {# pkglts, pyproject.project
[project]  # https://packaging.python.org/en/latest/specifications/pyproject-toml/
name = "statpairviz"
version = "1.0.1"
description = "Helper functions to annotate pairwise comparisons on plots"
readme = "README.rst"
requires-python = ">= 3.10"
license = {text = "cc_by_nc"}
authors = [
    {name = "revesansparole", email = "revesansparole@gmail.com"},
]
maintainers = [
    {name = "revesansparole", email = "revesansparole@gmail.com"},
    {name = "Jerome Chopard", email = "revesansparole@gmail.com"},
]
keywords = [
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
]

[project.optional-dependencies]
doc = [
    "sphinx",
    "sphinx-gallery",
    "sphinx-rtd-theme",
]
dvlpt = [
    "twine",
]
example = [
    "matplotlib",
]
test = [
    "coverage",
    "pytest",
    "pytest-cov",
    "pytest-mock",
]


[project.urls]
repository = "https://gitlab.com/revesansparole/statpairviz"
pip = "https://pypi.org/project/statpairviz/1.0.1/"
conda = "https://anaconda.org/revesansparole/statpairviz"
doc = "https://revesansparole.gitlab.io/statpairviz/"
pypi = "https://badge.fury.io/py/statpairviz"


[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ['*.json', '*.ini', '*.csv', '*.rst', '*.svg', ]

# #}
# {# pkglts, test, after pyproject.project
[tool.pytest.ini_options]
addopts = "--maxfail=2 -rf --cov=statpairviz"
# #}

# {# pkglts, pyproject.scripts
[project.scripts]
# #}

# {# pkglts, pyproject.gui_scripts
[project.gui-scripts]
# #}
