# Fields to fill out
analyst_name: "script_default"
site: "Kumeti at Rua Roa"
from_date: "2024-03-07 11:45"
# to_date: "2024-07-01 11:00"

# Hilltop Server Configuration
base_url: "http://hilltopdev.horizons.govt.nz/"
standard_hts_filename: "RawLoggerNet.hts"
# check_hts_filename: "HydrobotCheckData.hts"

# Data Source Configuration
standard_measurement_name: "Soil Moisture [Soil Moisture]"
# check_measurement_name: "Water Temperature Check [Water Temperature]"
frequency: "15min"

# Export configuration
export_file_name: "processed_sm.xml"

# Processing Configuration
defaults:
  delta: 5
  gap_limit: 12
  high_clip: 100
  low_clip: 0
  max_qc: 200
  span: 10

# Annalist Configuration
logfile: "hydrobot_logs.csv"
format:
  file: "%(asctime)s, %(analyst_name)s, %(function_name)s, %(site)s, %(measurement)s, %(from_date)s, %(to_date)s, %(message)s"
  stream: "%(function_name)s | %(measurement)s | %(from_date)s -> %(to_date)s | %(message)s"

# Survey123 SQL Configuration
s123_sql_server: "DBSurvey123Live.horizons.govt.nz"
s123_database: "survey123"
s123_query_type: "WaterTemp"
# s123_sql_driver: "SQL Server" # If on Windows
s123_sql_driver: "/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so.5.1" # If on WSL

inspection_expiry:
    500:
        months: 2
    0:
        months: 4

constant_check_shift: 0
